# Generated by Django 5.0.2 on 2025-04-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='placeholder@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
