# Generated by Django 5.0.2 on 2025-04-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_auto_20250407_0522"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
