# Generated by Django 5.0.2 on 2025-04-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_userprofile_address_userprofile_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="admin_department",
            field=models.CharField(
                blank=True, help_text="Department for administrators", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="admin_title",
            field=models.CharField(
                blank=True,
                help_text="Title/Position for administrators",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="address",
            field=models.TextField(blank=True, default=26),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("PARENT", "Parent"),
                    ("ADMINISTRATOR", "Administrator"),
                    ("CAREGIVER", "Caregiver"),
                ],
                max_length=20,
            ),
        ),
    ]
