# Generated by Django 5.0.2 on 2025-04-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "website",
            "0004_userprofile_admin_department_userprofile_admin_title_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="admin_department",
            field=models.CharField(
                blank=True,
                help_text="Required for administrators: Your department",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="admin_title",
            field=models.CharField(
                blank=True,
                help_text="Required for administrators: Your position or title",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("PARENT", "Parent"),
                    ("CAREGIVER", "Caregiver"),
                    ("ADMINISTRATOR", "Administrator"),
                ],
                max_length=20,
            ),
        ),
    ]
