# Generated by Django 5.0.2 on 2025-04-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_alter_userprofile_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="admin_department",
            field=models.CharField(
                blank=True,
                help_text="Optional: Your department",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="admin_title",
            field=models.CharField(
                blank=True,
                help_text="Optional: Your position or title",
                max_length=100,
                null=True,
            ),
        ),
    ]
