# Generated by Django 5.2 on 2026-04-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_alter_userprofile_admin_department_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "backend",
                    models.CharField(
                        choices=[("anthropic", "Anthropic"), ("ollama", "Ollama")],
                        default="anthropic",
                        max_length=20,
                    ),
                ),
                (
                    "anthropic_api_key",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "ollama_base_url",
                    models.CharField(default="http://localhost:11434", max_length=255),
                ),
                ("ollama_model", models.CharField(default="llama3", max_length=100)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "LLM Settings",
                "verbose_name_plural": "LLM Settings",
            },
        ),
    ]
