# Generated by Django 5.2 on 2026-04-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_add_llmsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmsettings",
            name="local_api_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Base URL for LM Studio / vLLM / llama.cpp (OpenAI-compatible)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="llmsettings",
            name="local_model",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Model name for the local backend",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="llmsettings",
            name="backend",
            field=models.CharField(
                choices=[
                    ("anthropic", "Anthropic"),
                    ("ollama", "Ollama"),
                    ("lmstudio", "LM Studio"),
                    ("vllm", "vLLM"),
                    ("llamacpp", "llama.cpp"),
                ],
                default="anthropic",
                max_length=20,
            ),
        ),
    ]
