# Generated by Django 5.2.17 on 2026-09-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_add_local_llm_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmsettings',
            name='ollama_base_url',
            field=models.CharField(default='http://ollama:12434', max_length=255),
        ),
        migrations.AlterField(
            model_name='llmsettings',
            name='ollama_model',
            field=models.CharField(default='llama3.2:1b', max_length=100),
        ),
    ]
