# Generated by Django 5.0.2 on 2025-04-05 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sage", "0002_alter_document_uploaded_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="uploaded_by",
        ),
    ]
