# Generated by Django 5.2 on 2026-03-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sage", "0004_document_analysis_document_uploaded_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="dish",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
