# Generated by Django 5.2 on 2026-03-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sage", "0005_dish_created_at_dish_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schedule",
            options={"ordering": ["day_of_week", "start_time"]},
        ),
        migrations.AddField(
            model_name="schedule",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="activity",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="agent",
            field=models.CharField(
                blank=True,
                choices=[
                    ("grace", "Grace"),
                    ("patience", "Patience"),
                    ("sage", "Sage"),
                    ("", "None"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="day_of_week",
            field=models.IntegerField(
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                ]
            ),
        ),
        migrations.AlterUniqueTogether(
            name="schedule",
            unique_together={("start_time", "day_of_week", "is_default")},
        ),
    ]
