# Generated by Django 5.2 on 2026-03-15 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enroll", "0003_add_child_activity"),
        ("sage", "0006_alter_schedule_options_schedule_is_default_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyPlanEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start_date", models.DateField()),
                ("scheduled_date", models.DateField()),
                ("start_time", models.TimeField()),
                (
                    "agent",
                    models.CharField(
                        choices=[
                            ("grace", "Grace"),
                            ("patience", "Patience"),
                            ("sage", "Sage"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "activity_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("is_static", models.BooleanField(default=False)),
                (
                    "guideline_activity",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "children",
                    models.ManyToManyField(
                        blank=True, related_name="weekly_activities", to="enroll.child"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_date", "start_time"],
            },
        ),
    ]
