# Generated by Django 5.2 on 2026-03-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sage", "0007_add_weekly_plan_entry"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="meal_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BREAKFAST", "Breakfast"),
                    ("AM_SNACK", "AM Snack"),
                    ("LUNCH", "Lunch"),
                    ("PM_SNACK", "PM Snack"),
                    ("SUPPER", "Supper"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
