# Generated by Django 5.2 on 2026-04-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sage", "0008_dish_meal_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="is_current",
            field=models.BooleanField(default=False),
        ),
    ]
