# Generated by Django 5.0.2 on 2025-04-04 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MotorCurriculum",
            fields=[
                (
                    "patienceeactivity",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "patienceactivity_picture",
                    models.ImageField(upload_to="graceactivity_pics/"),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("rating", models.IntegerField()),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="PhysicalActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("FINE", "Fine Motor"),
                            ("GROSS", "Gross Motor"),
                            ("HAND_EYE", "Hand-Eye Coordination"),
                            ("DANCE", "Dance & Movement"),
                            ("SPORTS", "Early Sports"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "age_range",
                    models.CharField(
                        choices=[
                            ("0-1", "0-1 years"),
                            ("1-2", "1-2 years"),
                            ("2-3", "2-3 years"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                ("materials", models.TextField()),
                ("safety_notes", models.TextField()),
                ("benefits", models.TextField()),
                ("modifications", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Physical Activities",
                "ordering": ["-created_at"],
            },
        ),
    ]
