# Generated by Django 5.2 on 2026-03-13 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patience", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="motorcurriculum",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "Motor Curriculum Activities",
            },
        ),
        migrations.RemoveField(
            model_name="motorcurriculum",
            name="date",
        ),
        migrations.RemoveField(
            model_name="motorcurriculum",
            name="patienceactivity_picture",
        ),
        migrations.RemoveField(
            model_name="motorcurriculum",
            name="patienceeactivity",
        ),
        migrations.RemoveField(
            model_name="motorcurriculum",
            name="rating",
        ),
        migrations.AddField(
            model_name="motorcurriculum",
            name="activity_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="motor_activity_pics/"
            ),
        ),
        migrations.AddField(
            model_name="motorcurriculum",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("FINE", "Fine Motor"),
                    ("GROSS", "Gross Motor"),
                    ("HAND_EYE", "Hand-Eye Coordination"),
                    ("BALANCE", "Balance & Coordination"),
                    ("SENSORY", "Sensory Motor"),
                ],
                default="GROSS",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="motorcurriculum",
            name="age_range",
            field=models.CharField(
                choices=[
                    ("0-1", "0-1 years"),
                    ("1-2", "1-2 years"),
                    ("2-3", "2-3 years"),
                    ("3-4", "3-4 years"),
                    ("4-5", "4-5 years"),
                ],
                default="2-3",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="motorcurriculum",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="motorcurriculum",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="motorcurriculum",
            name="developmental_goal",
            field=models.TextField(
                default="", help_text="What motor skill this activity develops"
            ),
        ),
        migrations.AddField(
            model_name="motorcurriculum",
            name="duration_minutes",
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name="motorcurriculum",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="motorcurriculum",
            name="materials",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="motorcurriculum",
            name="safety_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="motorcurriculum",
            name="title",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="motorcurriculum",
            name="description",
            field=models.TextField(
                default="", help_text="Step-by-step description of the activity"
            ),
        ),
    ]
