# Generated by Django 5.0.2 on 2025-04-04 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("child_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                ("child_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("child_address", models.CharField(max_length=100)),
                (
                    "child_gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        default="M",
                        max_length=1,
                    ),
                ),
                ("parent_name", models.CharField(max_length=100)),
                ("parent_address", models.CharField(max_length=100)),
                ("parent_phone", models.CharField(max_length=128)),
                ("parent_email", models.EmailField(max_length=100)),
                ("ok_to_text", models.BooleanField(default=True)),
                ("parent", models.BooleanField(default=True)),
                ("caretaker", models.BooleanField(default=True)),
                ("relative", models.BooleanField(default=True)),
                ("guardian", models.BooleanField(default=True)),
                ("other", models.BooleanField(default=True)),
                (
                    "parent_name_1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "parent_phone_1",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "parent_email_1",
                    models.EmailField(blank=True, max_length=100, null=True),
                ),
                (
                    "ok_to_text_1",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    "authorized_pickup_1",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    "parent_name_2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "parent_phone_2",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "parent_email_2",
                    models.EmailField(blank=True, max_length=100, null=True),
                ),
                (
                    "ok_to_text_2",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    "authorized_pickup_2",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    "parent_name_3",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "parent_phone_3",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "parent_email_3",
                    models.EmailField(blank=True, max_length=100, null=True),
                ),
                (
                    "ok_to_text_3",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    "authorized_pickup_3",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                ("date_of_enrollment", models.DateField()),
                ("date_of_withdrawal", models.DateField()),
                ("child_physician", models.CharField(max_length=100)),
                ("child_physician_phone", models.CharField(max_length=128)),
                ("preferred_hospital", models.CharField(max_length=100)),
                ("hospital_phone", models.CharField(max_length=128)),
                ("child_dentist", models.CharField(max_length=100)),
                ("dentist_phone", models.CharField(max_length=128)),
                ("child_allergies", models.CharField(max_length=100)),
                ("speech_therapy", models.BooleanField(default=True)),
                ("physical_therapy", models.BooleanField(default=True)),
                ("early_intervention", models.BooleanField(default=True)),
                ("other_therapy", models.BooleanField(default=True)),
                ("none_therapy", models.BooleanField(default=True)),
                (
                    "info_to_share",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                ("consent_to_treat", models.BooleanField(default=True)),
                ("consent_to_transport", models.BooleanField(default=True)),
                ("consent_to_trip", models.BooleanField(default=True)),
                ("understand_permissions", models.BooleanField(default=True)),
                ("agree_to_update", models.BooleanField(default=True)),
                ("agree_policies", models.BooleanField(default=True)),
                ("photo_release", models.BooleanField(default=True)),
                ("signature", models.CharField(max_length=100)),
                ("date_signed", models.DateField()),
                ("enrollment_date", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "enrolled_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrolled_students",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_modifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "student_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="enroll.student",
                    ),
                ),
                ("is_checked_in", models.BooleanField(default=False)),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Child",
                "verbose_name_plural": "Children",
                "db_table": "enroll_child",
            },
            bases=("enroll.student",),
        ),
        migrations.CreateModel(
            name="StudentRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("rating", models.IntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="enroll.child"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttendanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in", models.DateTimeField()),
                ("check_out", models.DateTimeField(blank=True, null=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_logs",
                        to="enroll.child",
                    ),
                ),
            ],
            options={
                "ordering": ["-check_in"],
            },
        ),
    ]
