# Generated by Django 5.0.2 on 2025-04-05 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enroll", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="child",
            table=None,
        ),
    ]
