# Generated by Django 5.2 on 2026-03-13 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grace", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="socialcurriculum",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "Social Curriculum Activities",
            },
        ),
        migrations.RemoveField(
            model_name="socialcurriculum",
            name="rating",
        ),
        migrations.AddField(
            model_name="socialcurriculum",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("EMOTIONAL", "Emotional Awareness"),
                    ("SHARING", "Sharing & Turn-Taking"),
                    ("EMPATHY", "Empathy Building"),
                    ("CONFLICT", "Conflict Resolution"),
                    ("SELF_REG", "Self-Regulation"),
                    ("SOCIAL_PLAY", "Social Play"),
                    ("COMMUNICATION", "Communication Skills"),
                ],
                default="SOCIAL_PLAY",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="socialcurriculum",
            name="age_range",
            field=models.CharField(
                choices=[
                    ("0-1", "0-1 years"),
                    ("1-2", "1-2 years"),
                    ("2-3", "2-3 years"),
                    ("3-4", "3-4 years"),
                    ("4-5", "4-5 years"),
                ],
                default="2-3",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="socialcurriculum",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="socialcurriculum",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="socialcurriculum",
            name="developmental_goal",
            field=models.TextField(
                default="",
                help_text="What social-emotional skill this activity develops",
            ),
        ),
        migrations.AddField(
            model_name="socialcurriculum",
            name="duration_minutes",
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name="socialcurriculum",
            name="group_size",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g. 2-4 children, individual, whole class",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="socialcurriculum",
            name="materials",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="socialcurriculum",
            name="author",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="socialcurriculum",
            name="description",
            field=models.TextField(
                default="", help_text="Step-by-step description of the activity"
            ),
        ),
        migrations.AlterField(
            model_name="socialcurriculum",
            name="title",
            field=models.CharField(default="", max_length=200),
        ),
    ]
